### ISSUE TITLE
There are some unrelated questions

### ISSUE THREAD

**Issue by zhefox** [clearbluejar/ghidriff#105]
How can I directly wget the execution version of the file I want?
such as “wget https://msdl.microsoft.com/download/symbols/clfs.sys/D929C6E56f000/clfs.sys -O ghidriffs/clfs.sys.x64.10.0.22621.2715”
D929C6E56f000 is 10.0.22621.2715
Where can I see the directory of all files?

**Comment by clearbluejar** [comment]
Are you referring to the command line section? Such as this one: https://gist.github.com/clearbluejar/b95ae854a92ee917cd0b5c7055b60282#download-original-pes ?

```
wget https://msdl.microsoft.com/download/symbols/ntkrnlmp.exe/F7E31BA91047000/ntkrnlmp.exe -O ntkrnlmp.exe.x64.10.0.22621.1344
wget https://msdl.microsoft.com/download/symbols/ntkrnlmp.exe/17B6B7221047000/ntkrnlmp.exe -O ntkrnlmp.exe.x64.10.0.22621.1413
```

These urls are generated using metadata from the PE file. If you want to large list of the files  I suggest checking out https://winbindex.m417z.com/?file=clfs.sys . This site will provide you all the versions / download links needed.

**Comment by zhefox** [comment]
thanks！

| |
ZHEFOX
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 10/18/2024 20:27 |
| To | clearbluejar/ghidriff ***@***.***> |
| Cc | ZheFox ***@***.***>,
Author ***@***.***> |
| Subject | Re: [clearbluejar/ghidriff] There are some unrelated questions (Issue #105) |

Are you referring to the command line section? Such as this one: https://gist.github.com/clearbluejar/b95ae854a92ee917cd0b5c7055b60282#download-original-pes ?

wget https://msdl.microsoft.com/download/symbols/ntkrnlmp.exe/F7E31BA91047000/ntkrnlmp.exe -O ntkrnlmp.exe.x64.10.0.22621.1344
wget https://msdl.microsoft.com/download/symbols/ntkrnlmp.exe/17B6B7221047000/ntkrnlmp.exe -O ntkrnlmp.exe.x64.10.0.22621.1413


These urls are generated using metadata from the PE file. If you want to large list of the files I suggest checking out https://winbindex.m417z.com/?file=clfs.sys . This site will provide you all the versions / download links needed.
