### ISSUE TITLE
Precision on markdown format

### ISSUE THREAD

**Issue by chrysn** [clearbluejar/ghidriff#54]
Having tried two markdown implementations that both did not even recognize the mermaid parts as figures (let alone would render them), I'm slowly zeroing down on `cmark --extension table` (or cmark-gfm?) (which still doesn't render mermaid but that could be a plugin issue).

Please consider adding a note in the README about which flavor of markdown the files are to make this easier to use.

**Comment by clearbluejar** [comment]
MermaidJS isn't everywhere, but it is in quite a few places. Its support is distinct from markdown and its available integrations are listed here. https://mermaid.js.org/ecosystem/integrations-community.html

I see your point though about being specific about the markdown/mermaidjs support. I can update the README to include specifics about mermaid. 

For markdown, I haven't strictly checked the format. Generally, I am trying to make sure it works in most places, but primarily I manually test in github and gitlab.   I will create another issue here to address the output, to make sure I follow some sort of standard. Likely I can use this tool https://pypi.org/project/pymarkdownlnt/ to verify my markdown output meets `cmark` and `gfm`.  Again mermaid support will vary.  

I will keep this issue open until I update the README.

**Comment by clearbluejar** [comment]
Closed as a part of the PR. Reopen if you think it isn't addressed.
